development:
  adapter: mysql
  database: taskmanager_dev
  username: rails
  password: rails_rocks
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  adapter: mysql
  database: taskmanager
  username: taskmanager
  password: iaeWo2ohcee
  socket: /var/run/mysqld/mysqld.sock
